# Generated by Django 3.2.11 on 2022-01-17 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0001_initial'),
        ('accounts', '0002_auto_20220115_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(null=True, upload_to='users/icon', verbose_name='アイコン'),
        ),
        migrations.AddField(
            model_name='user',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drawing.member', verbose_name='メンバー'),
        ),
    ]
