# Generated by Django 3.2.11 on 2022-02-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0004_auto_20220201_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_play',
        ),
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
        migrations.AlterField(
            model_name='room',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='パスワード'),
        ),
    ]
