# Generated by Django 3.2.11 on 2022-02-05 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0005_auto_20220201_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='round',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='ラウンド数'),
        ),
    ]
