# Generated by Django 3.2.11 on 2022-01-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220117_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='member',
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.TextField(null=True, verbose_name='自己紹介'),
        ),
    ]
