# Generated by Django 3.2.11 on 2022-01-18 14:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drawing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='memberNum',
        ),
        migrations.RemoveField(
            model_name='room',
            name='roomNum',
        ),
        migrations.AddField(
            model_name='member',
            name='score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='スコア'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='メンバー'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_play',
            field=models.BooleanField(default=False, verbose_name='プレイ中'),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '作成'), (2, '参加'), (3, '満室')], default=1, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='member',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.room', verbose_name='ルーム'),
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.member', verbose_name='メンバー')),
            ],
            options={
                'verbose_name': 'ChatLog',
                'verbose_name_plural': 'ChatLogs',
            },
        ),
    ]
