# Generated by Django 3.2.11 on 2022-02-01 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0003_alter_chatlog_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='entryNum',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)], verbose_name='参加人数'),
        ),
        migrations.AddField(
            model_name='room',
            name='level',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='medium', max_length=50, verbose_name='レベル'),
        ),
        migrations.AddField(
            model_name='room',
            name='mode',
            field=models.CharField(choices=[('絵当てゲーム', '絵当てゲーム'), ('伝言ゲーム', '伝言ゲーム')], default='絵当てゲーム', max_length=50, verbose_name='ゲームモード'),
        ),
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(max_length=50, null=True, verbose_name='パスワード'),
        ),
        migrations.AddField(
            model_name='room',
            name='round',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(7)], verbose_name='ラウンド数'),
        ),
    ]
